checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - "tests/"
build:
    environment:
        php: '5.5.0'
    dependencies:
        before:
            - mysql -uroot -e "create database IF NOT EXISTS users_management;"
            - mysql -uroot -e "CREATE USER 'users_management'@'localhost' IDENTIFIED BY 'zhhnqBF26wtnUnP9';"
            - mysql -uroot -e "GRANT ALL ON users_management.* TO 'users_management'@'localhost';"
            - mysql -uroot users_management < tests/usersManagement.sql
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

